AllCops:
  Include:
    - Gemfile
    - Guardfile
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - bin/*
    - db/schema.rb
    - test/dummy/db/schema.rb
  TargetRubyVersion: 2.3

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 39

Metrics/BlockLength:
  Exclude:
  - '**/*_spec.rb'
  - 'config/routes.rb'
  - '*.gemspec'
  ExcludedMethods: ['guard', 'included']

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 9

Naming/FileName:
  Exclude: ['*.gemspec']

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%i': '()'
    '%r': '{}'
    '%w': '()'

Style/RescueModifier:
  Enabled: false
