module Lt
  module Lcms
    module Lesson
      module Uploader
        class Gdoc
          def initialize: (untyped credentials) -> void
          def upload: (String name, untyped content, String content_type, ?(String | nil)? parent_folder_id) -> String

          private

          def service: -> untyped
        end
      end
    end
  end
end
